function str_summary = get_dynsys_summary(obj)
    str_header1 = strcat("Summary of ", class(obj), " instance:");
    str_header2 = strjoin(repmat({'-'}, 1, strlength(str_header1)), '');
    str_setup = strcat("  [Setup Option] ", obj.setup_option);
    str_x_u = strcat("  [Dimension] State: ", num2str(obj.xdim), ...
        ", Control input: ", num2str(obj.udim));
    str_clf_cbf = strcat("  [Num of value functions] CLF: ", num2str(obj.n_clf), ...
        ", CBF: ", num2str(obj.n_cbf));
    str_summary = strcat(strjoin([str_header1, str_header2, ...
        str_setup, str_x_u, str_clf_cbf], ...
        '\n'), '\n');
end
