function dydq_a = dydq_a_gen(obj,in1)
    %DYDQ_A_GEN
    %    DYDQ_A = DYDQ_A_GEN(IN1)

    %    This function was generated by the Symbolic Math Toolbox version 8.0.
    %    11-Dec-2019 16:46:17

    dydq_a = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0],[4,7]);
end